version: '3'

services:
    postgresdb:
        container_name: book_db
        image: postgres:latest
        volumes:
            - book_vol:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=bookpass
            - POSTGRES_USER=bookadmin
            - POSTGRES_DB=book
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - '5432:5432'
    spring-boot-jpa-docker-webapp:
        container_name: springboot-jpa
        image: techcheck/booklist
        depends_on:
            - postgresdb
        ports:
            - 9080:9080
        environment:
            - DB_HOST=postgresdb
            - DB_USER=bookadmin
            - DB_PASSWORD=bookpass
            - DB_NAME=book
            - DB_PORT=5432

volumes:
    book_vol: {}

networks:
    default:
